### ISSUE TITLE
Retry robot tests

### ISSUE THREAD

**Issue by ale-rt** [collective/robotsuite#17]
I have this patch:
```
def run(self, result=None):
    """ Retry test based on:
    https://stackoverflow.com/questions/7152428/can-python-unittest-automatically-reattempt-a-failed-testcase-suite  # noqa: E501
    """
    self.origTestMethodName = self._testMethodName
    self._testMethodName = "_testRetryWrapper"
    super(robotsuite.RobotTestCase, self).run(result)
    self._testMethodName = self.origTestMethodName


def _testRetryWrapper(self):
    testMethod = getattr(self, self.origTestMethodName)
    retryAttemptsLeft = 3
    logger.info(
        "Trying %r (%r attemps left)", self.origTestMethodName, retryAttemptsLeft
    )
    while True:
        try:
            testMethod()
            break
        except BaseException:
            if retryAttemptsLeft == 0:
                raise
            logger.warning(
                "Retrying %r (%r attemps left)",
                self.origTestMethodName,
                retryAttemptsLeft,
            )
            retryAttemptsLeft = retryAttemptsLeft - 1
            self.tearDown()


robotsuite.RobotTestCase.run = run
robotsuite.RobotTestCase._testRetryWrapper = _testRetryWrapper
```
what it does is that if a robot test is failing, it retries it one more time before declaring it failed.
If the second time the test runs the build on jenkins is marked as unstable (yellow dot).

You can see the result of a test run here:
- https://jenkins.quaive.net/job/quaive-master-pullrequest-robot-1/2204/

![image](https://user-images.githubusercontent.com/1300763/69477547-c57afe80-0de7-11ea-98e6-8845bef973c2.png)
![image](https://user-images.githubusercontent.com/1300763/69477570-e6435400-0de7-11ea-9980-0aaa8d30a0f6.png)

Everything is based on this stackoverflow answer:
https://stackoverflow.com/questions/7152428/can-python-unittest-automatically-reattempt-a-failed-testcase-suite
There are things that are perfectible, in my opinion but it might be interesting to have it.

If anybody as opinions before I make a PR it would be great to know!

**Comment by ale-rt** [comment]
CC @datakurre @plone/testing-team

**Comment by datakurre** [comment]
I’d prefer to see this as a more generic zope.testrunner feature to ensure and test setup and teardown are properly run... but I kinda understand that it could be much more work. Still, I’m not sure if possible test setup and teardown are taken into account here. 

Definitely this should be opt-in. For example, via a test suite class attribute. Robotsuite is generic Robot Framework wrapper for Python unittest and not all use is wrapping flaky Selenium tests 🤔

**Comment by ale-rt** [comment]
Thank you for your input @datakurre!
It seems to me that setup and teardown are properly run (many of the test cases would fail otherwise).
I have no hurry to push anything done bad because I already have a workaround in place.
So let's discuss this and investigate a proper way of doing that!

And, yes this should be an opt in feature, I was also thinking about making `retryAttemptsLeft` configurable

**Comment by datakurre** [comment]
Ok. Thanks.

Class attributes are already used to set test level for zope.testrunner, so setting amount of retries there should be ok.

https://github.com/plone/bobtemplates.plone/blob/eac846cccd046c891a1333d545406b09b3d0d82e/bobtemplates/plone/addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/tests/test_robot.py.bob#L21

**Comment by ale-rt** [comment]
> It seems to me that setup and teardown are properly run

I had the proof that this was a misconception, I will try to go deeper into this

**Comment by datakurre** [comment]
https://pypi.org/project/robotsuite/2.1.1/
