### ISSUE TITLE
Port tests - really needed?

### ISSUE THREAD

**Issue by 1letter** [collective/robotsuite#29]
@datakurre 

this package ist part of this issue: https://github.com/plone/Products.CMFPlone/issues/3813

is a port really needed? i don't see any selenium imports. I'm not that familiar with the subject matter "nix". Can you help Have you time?

**Comment by datakurre** [comment]
@1letter This package does not contain selenium tests, so this is probably on the list by accident.

This package provides wrapper running Robot Framework tests with zope.testrunner used by Plone tests.

This package probably only needs to be updated when Plone upgrades major Robot Framework updates.

Nix here is just my personal way to build test matrix with different Python and Robot Framework versions.
