### ISSUE TITLE
Can we get more debug information in Travis?

### ISSUE THREAD

**Issue by djowett** [collective/robotsuite#8]
Is it possible to get more information than the below for Travis failures? A line number would be nice, a stacktrace even nicer.

    Failure in test Scenario As an editor I can add new translation (robot/test_add_translation.robot)
    Traceback (most recent call last):
      File "/home/travis/build/plone/plone.app.multilingual/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
        testMethod()
      File "/home/travis/build/plone/plone.app.multilingual/eggs/robotsuite-1.7.0-py2.7.egg/robotsuite/__init__.py", line 461, in runTest
        assert last_status == 'PASS', last_message
    AssertionError: Text 'An English Document' did not appear in 30 seconds

**Comment by datakurre** [comment]
@djowett I'm afraid, this is won't fix.

When a real Python exception in Plone happen, I recall robotsuite trying to show the last seen exception. More than that is not easy. AFAIK the best available option is to use Travis test artifacts support to publish test reports with screenshots into S3. Something to make that or something similar easier would be great.

**Comment by djowett** [comment]
Ok thanks - this was a reaction to a message on Travis 
<https://travis-ci.org/plone/plone.app.multilingual/jobs/113152646#L1360> that 
said
"Artifacts support disabled for pull requests"

after a not so useful message in the AssertionError

However, I found the Artifacts support working in the branch (which I 
hadn't realised before).

Sorry to make a fuss!
